server:
  port: 8761

spring:
  application:
    name: Discovery

eureka:
  server:
    # 자체 보호 모드(Self-Preservation Mode)
    # 클라이언트의 heartbeat 부족 상황에서도 등록 정보를 유지하도록 Eureka 서버의 자체 보호 모드를 설정
    # 운영 환경에서 true 설정
    enable-self-preservation: false
  client:
    # 클라이언트가 자신을 Eureka 서버에 등록할지 여부를 결정하는 설정
    # 클러스터링 모드로 설정하는 경우, register-with-eureka를 true로 설정하여 서로의 Eureka 서버 간 정보를 공유하는 구조를 만듭니다.
    register-with-eureka: false
    # 클라이언트가 자신을 Eureka 서버에 등록할지 여부를 결정하는 설정
    fetch-registry: false
